const REGION_MAP = {
  "Alabama": "Southeast",
  "Alaska": "West",
  "Arizona": "Southwest",
  "Arkansas": "South",
  "California": "West",
  "Colorado": "Mountain",
  "Connecticut": "Northeast",
  "Delaware": "Northeast",
  "Florida": "Southeast",
  "Georgia": "Southeast",
  "Hawaii": "West",
  "Idaho": "Mountain",
  "Illinois": "Midwest",
  "Indiana": "Midwest",
  "Iowa": "Midwest",
  "Kansas": "Plains",
  "Kentucky": "South",
  "Louisiana": "South",
  "Maine": "Northeast",
  "Maryland": "Northeast",
  "Massachusetts": "Northeast",
  "Michigan": "Midwest",
  "Minnesota": "Midwest",
  "Mississippi": "South",
  "Missouri": "Midwest",
  "Montana": "Mountain",
  "Nebraska": "Plains",
  "Nevada": "Mountain",
  "New Hampshire": "Northeast",
  "New Jersey": "Northeast",
  "New Mexico": "Southwest",
  "New York": "Northeast",
  "North Carolina": "Southeast",
  "North Dakota": "Plains",
  "Ohio": "Midwest",
  "Oklahoma": "South",
  "Oregon": "West",
  "Pennsylvania": "Northeast",
  "Rhode Island": "Northeast",
  "South Carolina": "Southeast",
  "South Dakota": "Plains",
  "Tennessee": "South",
  "Texas": "Southwest",
  "Utah": "Mountain",
  "Vermont": "Northeast",
  "Virginia": "Southeast",
  "Washington": "West",
  "West Virginia": "South",
  "Wisconsin": "Midwest",
  "Wyoming": "Mountain",
};

const REGIONS = [
  "West",
  "Southwest",
  "Mountain",
  "Plains",
  "Midwest",
  "South",
  "Southeast",
  "Northeast",
];

const METROS = [
  { city: "Los Angeles", state: "California", lat: 34.05, lon: -118.24, weight: 3.9 },
  { city: "San Francisco", state: "California", lat: 37.77, lon: -122.42, weight: 2.6 },
  { city: "San Diego", state: "California", lat: 32.72, lon: -117.16, weight: 1.3 },
  { city: "Seattle", state: "Washington", lat: 47.61, lon: -122.33, weight: 1.9 },
  { city: "Portland", state: "Oregon", lat: 45.52, lon: -122.68, weight: 1.2 },
  { city: "Phoenix", state: "Arizona", lat: 33.45, lon: -112.07, weight: 1.8 },
  { city: "Denver", state: "Colorado", lat: 39.74, lon: -104.99, weight: 1.6 },
  { city: "Las Vegas", state: "Nevada", lat: 36.17, lon: -115.14, weight: 1.1 },
  { city: "Dallas", state: "Texas", lat: 32.78, lon: -96.80, weight: 2.7 },
  { city: "Houston", state: "Texas", lat: 29.76, lon: -95.37, weight: 2.9 },
  { city: "Austin", state: "Texas", lat: 30.27, lon: -97.74, weight: 1.2 },
  { city: "San Antonio", state: "Texas", lat: 29.42, lon: -98.49, weight: 1.3 },
  { city: "Chicago", state: "Illinois", lat: 41.88, lon: -87.63, weight: 2.7 },
  { city: "Minneapolis", state: "Minnesota", lat: 44.98, lon: -93.26, weight: 1.3 },
  { city: "Detroit", state: "Michigan", lat: 42.33, lon: -83.05, weight: 1.1 },
  { city: "St. Louis", state: "Missouri", lat: 38.63, lon: -90.20, weight: 1.0 },
  { city: "Atlanta", state: "Georgia", lat: 33.75, lon: -84.39, weight: 1.8 },
  { city: "Miami", state: "Florida", lat: 25.76, lon: -80.19, weight: 1.4 },
  { city: "Orlando", state: "Florida", lat: 28.54, lon: -81.38, weight: 1.1 },
  { city: "Nashville", state: "Tennessee", lat: 36.16, lon: -86.78, weight: 0.9 },
  { city: "Charlotte", state: "North Carolina", lat: 35.23, lon: -80.84, weight: 1.0 },
  { city: "Washington, DC", state: "Virginia", lat: 38.90, lon: -77.04, weight: 1.4 },
  { city: "Philadelphia", state: "Pennsylvania", lat: 39.95, lon: -75.17, weight: 1.5 },
  { city: "New York City", state: "New York", lat: 40.71, lon: -74.00, weight: 3.1 },
  { city: "Boston", state: "Massachusetts", lat: 42.36, lon: -71.06, weight: 1.2 },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { REGION_MAP, REGIONS, METROS };
} else {
  window.FacilityData = { REGION_MAP, REGIONS, METROS };
}
